services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/expenses
    ports:
      - "8000:8000"

volumes:
  pgdata:
