[tool.mypy]
python_version = "3.13"
strict = true
ignore_missing_imports = false
check_untyped_defs = true
disallow_untyped_defs = true
disallow_any_unimported = true
disallow_any_expr = true
disallow_any_decorated = true
disallow_any_explicit = true
disallow_subclassing_any = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
show_error_codes = true
pretty = true
namespace_packages = true
explicit_package_bases = true

[tool.ruff]
target-version = "py313"
line-length = 100

[tool.ruff.lint]
# Enable all relevant rule sets for strict linting
select = [
  "E",    # pycodestyle errors
  "F",    # pyflakes
  "B",    # flake8-bugbear
  "I",    # isort
  "UP",   # pyupgrade
  "C4",   # flake8-comprehensions
  "RUF",  # ruff-specific rules
  "T20",  # flake8-print (forbids print)
  "DTZ",  # flake8-datetimez
  "SIM",  # flake8-simplify
  "N",    # pep8-naming
  "A",    # flake8-builtins (avoid shadowing built-ins)
]
ignore = []

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

