name: Ruff Lint

on: [push]

jobs:
  lint:
    name: Ruff Check and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Run ruff check (lint)
        run: ruff check .

      - name: Run ruff format (check only)
        run: ruff format --check .
